name: Clone Private Repository

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone private repository
        uses: actions/checkout@v2
        with:
          repository: kerzendorf-group/group-data
          ref: main
          token: ${{ secrets.ACCESS_DATA }}
          path: group-data
