name: Clone repo

on:
  workflow_dispatch:

jobs:
  clone-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Clone or fetch kerzendorf-group.github.io
        run: |
          if [ ! -d "kerzendorf-group.github.io" ]; then
            git clone https://${{ secrets.ACCESS_DATA }}@github.com/kerzendorf-group/kerzendorf-group.github.io.git
          else
            cd kerzendorf-group.github.io
            git fetch origin
            git checkout main
          fi

      - name: Clone or fetch group-data
        run: |
          if [ ! -d "group-data" ]; then
            git clone https://${{ secrets.ACCESS_DATA }}@github.com/kerzendorf-group/group-data.git
          else
            cd group-data
            git fetch origin
            git checkout main
          fi

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Clone my-other-repo"
          git push
