name: Copy & create directories

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Delete content"]
    types:
      - completed

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Create Directories
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: |
          mkdir kerzendorf-group.github.io/people
          mkdir kerzendorf-group.github.io/sub_research

      - name: Copy Assets
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: cp -r assets/ kerzendorf-group.github.io/$ACCESS_DATA

      - name: Copy Images
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: cp -r group-data/images/ kerzendorf-group.github.io/$ACCESS_DATA

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update files"
          git push
