name: "Push directory to another repository"
description: "Useful to push files to another repository to be used, for example, via github pages"
inputs:
  source-directory:
    description: "images/"
    required: true
  destination-github-username:
    description: "kerzendorf-group"
    required: true
  destination-repository-name:
    description: "groupwebsite_generator"
    required: true
  user-email:
    description: "action@github.com"
    required: true
  destination-repository-username:
    description: "[Optional] Username/organization for the destination repository"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.source-directory }}
    - ${{ inputs.destination-github-username }}
    - ${{ inputs.destination-repository-name }}
    - ${{ inputs.user-email }}
    - ${{ inputs.destination-repository-username }}
branding:
  icon: "git-commit"
  color: "green"
