name: Delete old website content

on:
  workflow_dispatch:

jobs:
  clone-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Delete content
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: find kerzendorf-group.github.io* -maxdepth 0 ! -name .gitignore ! -name .github ! -name .git -exec rm -rv {} \;

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Cleaned repository"
          git push
