name: Dir

on:
  workflow_dispatch:

jobs:
  Update_website:
    name: Updating website
    runs-on: ubuntu-latest
    steps:

      - name: List 
        run: |
          ls -a

      - name: cd ..
        run: |
          cd ..
          ls -a
          cd groupwebsite_generator
          ls -a

    