name: Dir

on:
  workflow_dispatch:

jobs:
  Update_website:
    name: Updating website
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: List 
        run: |
          ls -a

      - name: cd ..
        run: |
          cd ..
          ls -a

      - name: Setup directories inside kerzendorf-group.github.io
        run: |
          cd . 
          ls -a

    