name: Update group-data

on:
  push:
    paths:
      - "**"
  workflow_dispatch:

jobs:
  subtree_pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "action@github.com"
          git config credential.helper "store --file=.git/credentials"

      - name: Git Subtree Pull
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_DATA }}
        run: |
          git subtree pull --prefix=group-data git@github.com:kerzendorf-group/group-data.git main --squash

      - name: Commit and Push Changes
        run: |
          git commit -m "Update group-data subtree" -a
          git push origin main
