name: Update group-data

on:
  push:
    paths:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: kerzendorf-group/group-data
          ref: main
          token: ${{ secrets.ACCESS_DATA }}

      - name: Pull group-data repository
        run: |
          git subtree pull --prefix=group-data https://github.com/kerzendorf-group/group-data.git main --squash

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update group-data repository"
          git push origin main
