name: Image folder Sync

on:
  push:
    paths:
      - "images/**"
  workflow_dispatch:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Copy the changes made to 'images' folder to groupwebsite_generator
      - name: Push images folder to groupwebsite_generator
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "images/" # Folder to copy
          destination_repo: "kerzendorf-group/groupwebsite_generator" # Target repo
          destination_folder: "/" # Folder where to copy it
          user_email: "action@github.com"
          user_name: "github-actions"
          commit_message: "AUTO: Copied folder from group-data repository"
          git_server: "github.com"

  delete-file:
    runs-on: ubuntu-latest
    needs: copy-file
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Delete the deleted files from 'images' folder from groupwebsite_generator
      - name: Delete images folder from groupwebsite_generator
        uses: dmnemec/delete_file_from_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ env.API_TOKEN_GITHUB }}
        with:
          files_to_delete: "images/" # Folder to delete
          target_repo: "kerzendorf-group/groupwebsite_generator" # Target repo
          user_email: "action@github.com"
          user_name: "github-actions"
          commit_message: "AUTO: Deleted folder from groupwebsite_generator repository"
          git_server: "github.com"
