name: Sync Images

on:
  workflow_dispatch:
  push:
    paths:
      - "images/**"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v2
        with:
          repository: kerzendorf-group/group-data
          ref: master
          token: ${{ secrets.DISPATCH_VAR }}
          path: private-repo

      - name: Checkout public repository
        uses: actions/checkout@v2
        with:
          repository: kerzendorf-group/groupwebsite_generator
          ref: master
          token: ${{ secrets.DISPATCH_VAR }}
          path: public-repo

      - name: Sync images
        run: |
          rsync -a --delete private-repo/images/ public-repo/images/

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Sync images from private to public repository"
          add: public-repo
          author_name: Your Name
          author_email: your.email@example.com
          signoff: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
