name: Sync Images
on:
  workflow_dispatch:
  push:
    paths:
      - images/**
  repository_dispatch:
jobs:
  sync_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout group_web
        uses: actions/checkout@v2
        with:
          repository: kerzendorf-group/group_data
          ref: main
          path: group_data
      - name: Checkout groupwebsite_generator
        uses: actions/checkout@v2
        with:
          repository: groupwebsite_generator
          ref: main
          path: groupwebsite_generator
      - name: Sync images
        uses: actions/sync-repo@v2
        with:
          source-repo: kerzendorf-group/group_data
          source-path: images/
          destination-path: groupwebsite_generator/images/
          github-token: ${{ secrets.GITHUB_TOKEN }}
