name: Image Folder Sync

on:
  push:
    paths:
      - "images/**"
  workflow_dispatch:

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: List changed files
        id: list_changes
        run: echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} images/)"

      - name: Copy changed files to target repository
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: images
        if: steps.list_changes.outputs.files != ''

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: kerzendorf-group/groupwebsite_generator
          ref: main

      - name: Restore images folder from source repository
        if: steps.list_changes.outputs.files != ''
        run: |
          rm -rf images
          mkdir images
          cp -r ${{ github.workspace }}/images/* images/

      - name: Commit and push changes
        if: steps.list_changes.outputs.files != ''
        run: |
          git add -A
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"
          git commit -m "AUTO: Sync images folder from source repository"
          git push
