name: Image Sync

on:
  push:
    paths:
      - "images/**"
    workflow_dispatch:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Copy the 'images' folder
      - name: Push images folder to groupwebsite_generator
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "images/" # Folder to copy
          destination_repo: "kerzendorf-group/groupwebsite_generator" # Target repo
          destination_folder: "/" # Folder where to copy it
          user_email: "action@github.com"
          user_name: "github-actions"
          commit_message: "AUTO: Copied folder from group-data repository"
          git_server: "github.com"
