name: LIST

on:
  workflow_dispatch:

jobs:
  create_files:
    runs-on: ubuntu-latest
    steps:
      - name: List Repo
        uses: actions/checkout@v2

      - name: LIST
        run: |
          ls -a group-data
