name: Push website

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  push-subtree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Push to website repo
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: |
          cd kerzendorf-group.github.io
          git add .
          git commit -m "Pushing website"
          git push
