name: Push Website

on:
  workflow_dispatch:

jobs:
  create_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Push website
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: |

      - name: Copy Assets
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: cp -r assets kerzendorf-group.github.io/

      - name: Copy Images
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: cp -r group-data/images kerzendorf-group.github.io/

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Pushing website files"
          cd .. 
          git subtree push --prefix=kerzendorf-group.github.io https://github.com/kerzendorf-group/kerzendorf-group.github.io.git main --squash
          git push
