name: Push website

on:
  workflow_dispatch:

jobs:
  push-subtree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config credential.helper store

      - name: Push changes to repository
        run: |
          git subtree push --prefix=kerzendorf-group.github.io https://github.com/kerzendorf-group/kerzendorf-group.github.io.git main

        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_DATA}}
