name: Push website

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Build and deploy changes
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: |
          cd kerzendorf-group.github.io
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Deploy changes to kerzendorf-group.github.io"
          git push
