name: Remove repositories

on:
  workflow_dispatch:

jobs:
  clone-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Remove kerzendorf-group.github.io
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: |
          git rm --cached kerzendorf-group.github.io
          rm -rf kerzendorf-group.github.io

      - name: Remove group-data
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: |
          git rm --cached group-data
          rm -rf group-data

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Removed cloned repo"
          git push
