name: Update Group Website

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Check Webhook Dispatch"]

jobs:
  Update_website:
    name: Updating website
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone repositories
        run: |
          git clone git@github.com:deepthought-initiative/dti_group_data.git
          git clone git@github.com:deepthought-initiative/dtiwebsite_generator.git
          git clone git@github.com:deepthought-initiative/deepthought-initiative.github.io.git

      - name: List clones
        run: |
          ls -a

      - name: Clear cloned website repo
        run: |
          cd deepthought-initiative.github.io
          rm -rf index.html Research.html Contact.html People.html Support.html
          rm -rf assets website_files members sub_research support_images

      - name: Setup directories inside deepthought-initiative.github.io
        run: |
          cd deepthought-initiative.github.io
          mkdir members sub_research
          cp -r ../dti_group_data/website_data/website_files ./
          cp -r ../dti_group_data/website_data/support_images ./
          cp -r ../dtiwebsite_generator/assets ./
          rsync -av --exclude '*.json' --exclude 'jsons' ../dti_group_data/members/ ./members

      - name: Setup directories inside dti_group_data
        run: |
          cd dti_group_data
          mkdir members/common
          mkdir website_data/research/sub_research_data/combined


      - name: Install Jupyter and Python3
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo -H pip3 install --upgrade pip
          pip3 install jupyter

      - name: Run Notebooks
        run: |
          cd dtiwebsite_generator
          jupyter nbconvert --to python notebooks/*.ipynb
          python3 notebooks/jsons_prep.py
          python3 notebooks/create_htmls.py
          #for python_file_name in $(find notebooks -name "*.py")
          # do
          #    python3 "$python_file_name"
          #  done

      - name: Push Website
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: |
          cd deepthought-initiative.github.io
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Pushed from website generator"
          git push
